import Head   from 'next/head'
import Image  from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from '../components/banner';
import Card   from '../components/card';

import { loadPosts } from '../lib/data-four';

export async function getStaticProps(){
  let coffeeStores = await loadPosts();
return {
  props:{
    coffeeStores
  }
}
}


export default function Home(props) {
const handleOnBannerBtnClick = () => {
    console.log("I am working")
}
  
console.log(props.coffeeStores[0].id)

  if(props.coffeeStores[0].id != "Error1"){
  return (
    <div className={styles.container}>
      <Head>
        <title>Imtaki Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a style={{color:"white"}} href="https://nextjs.org">IMTAKI</a>
        </h1>
        <Banner buttonText="Yakındaki dukanları gör" handleOnClick={handleOnBannerBtnClick}/>

     {props.coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Toronto stores</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map((coffeeStore) => {
                const Myimg = coffeeStore.url + ".png"
                if(coffeeStore.url.length>0){
                    return (
                      <Card
                        key={coffeeStore.id}
                        name={coffeeStore.title}
                        imgUrl={Myimg}
                        href={`/coffee-store/${coffeeStore.id}`}
                        className={styles.card}
                      />
                    );
                  }
              })}
            </div>
          </>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
  }
}
